### ISSUE TITLE
module 'bionetwork' has no attribute 'activation'

### ISSUE THREAD

**Issue by ctboughter** [Lauffenburger-Lab/LEMBAS#1]
Just finished reading this great paper! I'm trying to recreate Fig1B and in running the function getting the above error.

It appears that bionetwork.py has no function "activation". I think this creates downstream issues elsewhere, as I also tried running the following:

python synthNetDataScreen.py --selectedCondition 10

and get a similar error:

torch.nn.modules.module.ModuleAttributeError: 'bionet' object has no attribute 'activation'

Apologies if this is a simple fix, but I'm new to pytorch. I appreciate any help!

**Comment by avlant** [comment]
Ok, I have pushed working versions of these two files.

The reviewers asked me to test several activation functions, so I had to rebuild the model so that the activation function could be specified manually. I thought I had updated all files affected by the new code, but I apparently missed these two.
